version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: reactiveDemo
    environment:
      POSTGRES_USER: hazem
      POSTGRES_PASSWORD: hazem
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    restart: unless-stopped
