spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo
    username: hazem
    password: hazem
  
  # Configuration pour Liquibase (utilise JDBC)
  liquibase:
    url: jdbc:postgresql://localhost:5432/demo
    user: hazem
    password: hazem

    change-log: "classpath:db/migration/master-changelog.xml"
    drop-first: false
    enabled: true
    
  # Configuration de la source de données JDBC (utilisée par Liquibase)
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: hazem
    password: hazem
    driver-class-name: org.postgresql.Driver


